stages:
  - lint
  - build
  - test

Lint:
  stage: lint
  tags:
    - bfs
  script: 
    - cpplint --verbose=0 src/airdata.h
    - cpplint --verbose=0 src/airdata_constants.h
    - cpplint --verbose=0 src/airdata.cpp
Compile:
  stage: build
  tags:
    - bfs
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/airdata_test

Test Airdata:
  stage: test
  tags:
    - bfs
  script:
    - ./build/airdata_test
